[package]
name = "adventofcode"
version = "0.1.0"
authors = ["Robert Krahn <robert.krahn@gmail.com>"]
edition = "2018"

[dependencies]
itertools = "0.8.1"
regex = "1.3.1"
chrono = "0.4.9"
reqwest = "0.9.22"
cookie = "0.12.0"
