[package]
name = "aoc-rksm-2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = "2.3.1"
env_logger = "0.9.0"
log = "0.4.14"
anyhow = "1.0.47"
itertools = "0.10.1"
bitvec = "0.22.3"

